In [188]:
# importing relevant packages
import numpy as np
import pandas as pd
from datetime import datetime

In [189]:
pd.__version__

'2.3.3'

In [190]:
nums = [1, 2, 3, 4, 5] # list
s = pd.Series(nums)
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [191]:
nums = (1, 2, 3, 4, 5) # tuple
s = pd.Series(nums)
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [192]:
list(s.index)

[0, 1, 2, 3, 4]

In [193]:
s.values

array([1, 2, 3, 4, 5])

In [194]:
nums = [1, 2, 3, 4, 5] # list
s = pd.Series(nums, index=('A', 'B', 'C', 'D', 'E'))
print(s)
print(type(s))

A    1
B    2
C    3
D    4
E    5
dtype: int64
<class 'pandas.core.series.Series'>

In [195]:
s.A

np.int64(1)

In [196]:
s.E

np.int64(5)

In [197]:
s.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [198]:
fruits = ['Orange','Banana','Mango']
fruits = pd.Series(fruits,  index=['O', 'B', 'M'])
print(fruits)

O    Orange
B    Banana
M     Mango
dtype: object

In [199]:
dct = {
    'name':'Asabeneh',
    'country':'Finland',
    'city':'Helsinki'
}
s = pd.Series(dct)
print(s)

name       Asabeneh
country     Finland
city       Helsinki
dtype: object

In [200]:
s = pd.Series(10, index = [1, 2, 3])
print(s)

1    10
2    10
3    10
dtype: int64

In [201]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [202]:
s = pd.Series(np.linspace(5, 20, 100)) # linspace(starting, end, items)
print(s)

0      5.000000
1      5.151515
2      5.303030
3      5.454545
4      5.606061
        ...
95    19.393939
96    19.545455
97    19.696970
98    19.848485
99    20.000000
Length: 100, dtype: float64

In [203]:
copied_fruits = fruits.copy()
copied_fruits

O    Orange
B    Banana
M     Mango
dtype: object

In [204]:
fruits['O'] = 'Onion'

In [205]:
fruits

O     Onion
B    Banana
M     Mango
dtype: object

In [206]:
copied_fruits

O    Orange
B    Banana
M     Mango
dtype: object

In [207]:
data = [
    ['Asabeneh', 'Finland', 'Helsink'], 
    ['David', 'UK', 'London'],
    ['John', 'Sweden', 'Stockholm']
]


df = pd.DataFrame(data, columns =  ['Name', 'Country', 'City'])
# df.index = ['A', 'B', 'C']
# df
df

       Name  Country       City
0  Asabeneh  Finland    Helsink
1     David       UK     London
2      John   Sweden  Stockholm

In [208]:
data = {
    'Name': ['Asabeneh', 'David', 'John'], 
    'Country':['Finland', 'UK', 'Sweden'], 
    'City': ['Helsiki', 'London', 'Stockholm']
}
df = pd.DataFrame(data)
df

       Name  Country       City
0  Asabeneh  Finland    Helsiki
1     David       UK     London
2      John   Sweden  Stockholm

In [209]:
data = [
    {'Name': 'Asabeneh', 'Country': 'Finland', 'City': 'Helsinki'},
    {'Name': 'David', 'Country': 'UK', 'City': 'London'},
    {'Name': 'John', 'Country': 'Sweden', 'City': 'Stockholm'}
]
df = pd.DataFrame(data)
df

       Name  Country       City
0  Asabeneh  Finland   Helsinki
1     David       UK     London
2      John   Sweden  Stockholm

In [210]:
list(df.columns)

['Name', 'Country', 'City']

In [211]:
df.shape

(3, 3)

In [212]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Country  3 non-null      object
 2   City     3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [213]:
data = [
    {"Name": "Asabeneh", "Country":"Finland","City":"Helsinki"},
    {"Name": "David", "Country":"UK","City":"London"},
    {"Name": "John", "Country":"Sweden","City":"Stockholm"},
    {"Name": "Eyob", "Country":"Finland","City":"Espoo"},
    {"Name": "Pawel", "Country":"Poland","City":"Warsaw"},
    {"Name": "Mahlet", "Country":"Ethiopia","City":"Addis Ababa"},
    {"Name": "Thomas", "Country":"Ethiopia","City":"Bahir Dar"},
    {"Name": "Lidiya", "Country":float('NaN'),"City":float('NaN')
    }
]
df = pd.DataFrame(data)
df

       Name   Country         City
0  Asabeneh   Finland     Helsinki
1     David        UK       London
2      John    Sweden    Stockholm
3      Eyob   Finland        Espoo
4     Pawel    Poland       Warsaw
5    Mahlet  Ethiopia  Addis Ababa
6    Thomas  Ethiopia    Bahir Dar
7    Lidiya       NaN          NaN

In [214]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Country  7 non-null      object
 2   City     7 non-null      object
dtypes: object(3)
memory usage: 324.0+ bytes

In [215]:
df

       Name   Country         City
0  Asabeneh   Finland     Helsinki
1     David        UK       London
2      John    Sweden    Stockholm
3      Eyob   Finland        Espoo
4     Pawel    Poland       Warsaw
5    Mahlet  Ethiopia  Addis Ababa
6    Thomas  Ethiopia    Bahir Dar
7    Lidiya       NaN          NaN

In [216]:
weights = [74, 78, 68, 108, 102, 58, 52, float('NaN')]
df['Weight'] = weights
df

       Name   Country         City  Weight
0  Asabeneh   Finland     Helsinki    74.0
1     David        UK       London    78.0
2      John    Sweden    Stockholm    68.0
3      Eyob   Finland        Espoo   108.0
4     Pawel    Poland       Warsaw   102.0
5    Mahlet  Ethiopia  Addis Ababa    58.0
6    Thomas  Ethiopia    Bahir Dar    52.0
7    Lidiya       NaN          NaN     NaN

In [217]:
heights = [173, 175, 169, 173, 195,168, 170, float('NaN')]
df['Height'] = heights
df

       Name   Country         City  Weight  Height
0  Asabeneh   Finland     Helsinki    74.0   173.0
1     David        UK       London    78.0   175.0
2      John    Sweden    Stockholm    68.0   169.0
3      Eyob   Finland        Espoo   108.0   173.0
4     Pawel    Poland       Warsaw   102.0   195.0
5    Mahlet  Ethiopia  Addis Ababa    58.0   168.0
6    Thomas  Ethiopia    Bahir Dar    52.0   170.0
7    Lidiya       NaN          NaN     NaN     NaN

In [218]:
df['Height'] = df['Height'] * 0.01
df

       Name   Country         City  Weight  Height
0  Asabeneh   Finland     Helsinki    74.0    1.73
1     David        UK       London    78.0    1.75
2      John    Sweden    Stockholm    68.0    1.69
3      Eyob   Finland        Espoo   108.0    1.73
4     Pawel    Poland       Warsaw   102.0    1.95
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70
7    Lidiya       NaN          NaN     NaN     NaN

In [219]:
weights = df['Weight']
heights = df['Height']
bmi_lst = []
for item in zip(weights, heights):
    mass, height = item
    bmi = mass / (height * height)
    bmi_lst.append(bmi)
print(bmi_lst)


df['BMI'] = bmi_lst

[24.725182932941294, 25.46938775510204, 23.80869017191275, 36.08540211834675, 26.824457593688365, 20.549886621315196, 17.99307958477509, nan]

In [220]:
df

       Name   Country         City  Weight  Height        BMI
0  Asabeneh   Finland     Helsinki    74.0    1.73  24.725183
1     David        UK       London    78.0    1.75  25.469388
2      John    Sweden    Stockholm    68.0    1.69  23.808690
3      Eyob   Finland        Espoo   108.0    1.73  36.085402
4     Pawel    Poland       Warsaw   102.0    1.95  26.824458
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68  20.549887
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70  17.993080
7    Lidiya       NaN          NaN     NaN     NaN        NaN

In [221]:
df['BMI'] = round(df['BMI'], 1)

In [222]:
df

       Name   Country         City  Weight  Height   BMI
0  Asabeneh   Finland     Helsinki    74.0    1.73  24.7
1     David        UK       London    78.0    1.75  25.5
2      John    Sweden    Stockholm    68.0    1.69  23.8
3      Eyob   Finland        Espoo   108.0    1.73  36.1
4     Pawel    Poland       Warsaw   102.0    1.95  26.8
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68  20.5
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70  18.0
7    Lidiya       NaN          NaN     NaN     NaN   NaN

In [223]:
birth_year = ['1769', '1985', '1990', '1983', '1985','1995', '1999', float('NaN')]
df['Birth Year'] = birth_year

In [224]:
df

       Name   Country         City  Weight  Height   BMI Birth Year
0  Asabeneh   Finland     Helsinki    74.0    1.73  24.7       1769
1     David        UK       London    78.0    1.75  25.5       1985
2      John    Sweden    Stockholm    68.0    1.69  23.8       1990
3      Eyob   Finland        Espoo   108.0    1.73  36.1       1983
4     Pawel    Poland       Warsaw   102.0    1.95  26.8       1985
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68  20.5       1995
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70  18.0       1999
7    Lidiya       NaN          NaN     NaN     NaN   NaN        NaN

In [225]:
df_copy = df.copy()

In [226]:
df_copy.drop('Name', axis = 1, inplace=True)

In [227]:
df

       Name   Country         City  Weight  Height   BMI Birth Year
0  Asabeneh   Finland     Helsinki    74.0    1.73  24.7       1769
1     David        UK       London    78.0    1.75  25.5       1985
2      John    Sweden    Stockholm    68.0    1.69  23.8       1990
3      Eyob   Finland        Espoo   108.0    1.73  36.1       1983
4     Pawel    Poland       Warsaw   102.0    1.95  26.8       1985
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68  20.5       1995
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70  18.0       1999
7    Lidiya       NaN          NaN     NaN     NaN   NaN        NaN

In [228]:
df_copy

    Country         City  Weight  Height   BMI Birth Year
0   Finland     Helsinki    74.0    1.73  24.7       1769
1        UK       London    78.0    1.75  25.5       1985
2    Sweden    Stockholm    68.0    1.69  23.8       1990
3   Finland        Espoo   108.0    1.73  36.1       1983
4    Poland       Warsaw   102.0    1.95  26.8       1985
5  Ethiopia  Addis Ababa    58.0    1.68  20.5       1995
6  Ethiopia    Bahir Dar    52.0    1.70  18.0       1999
7       NaN          NaN     NaN     NaN   NaN        NaN

In [229]:
df_copy.drop(columns='Country', axis = 1, inplace=True)

In [230]:
df_copy

          City  Weight  Height   BMI Birth Year
0     Helsinki    74.0    1.73  24.7       1769
1       London    78.0    1.75  25.5       1985
2    Stockholm    68.0    1.69  23.8       1990
3        Espoo   108.0    1.73  36.1       1983
4       Warsaw   102.0    1.95  26.8       1985
5  Addis Ababa    58.0    1.68  20.5       1995
6    Bahir Dar    52.0    1.70  18.0       1999
7          NaN     NaN     NaN   NaN        NaN

In [231]:
df_copy.drop(columns=['City', 'BMI', 'Weight'], axis = 1, inplace=True)

In [232]:
df_copy

   Height Birth Year
0    1.73       1769
1    1.75       1985
2    1.69       1990
3    1.73       1983
4    1.95       1985
5    1.68       1995
6    1.70       1999
7     NaN        NaN

In [233]:
df

       Name   Country         City  Weight  Height   BMI Birth Year
0  Asabeneh   Finland     Helsinki    74.0    1.73  24.7       1769
1     David        UK       London    78.0    1.75  25.5       1985
2      John    Sweden    Stockholm    68.0    1.69  23.8       1990
3      Eyob   Finland        Espoo   108.0    1.73  36.1       1983
4     Pawel    Poland       Warsaw   102.0    1.95  26.8       1985
5    Mahlet  Ethiopia  Addis Ababa    58.0    1.68  20.5       1995
6    Thomas  Ethiopia    Bahir Dar    52.0    1.70  18.0       1999
7    Lidiya       NaN          NaN     NaN     NaN   NaN        NaN

In [234]:
df_copy.drop([1, 2, 3, 4], axis = 0)

   Height Birth Year
0    1.73       1769
5    1.68       1995
6    1.70       1999
7     NaN        NaN

In [241]:
now = datetime.now()
current_year = now.year
print(current_year)
df['Current Year'] = current_year

2026

In [242]:
df

,Name,Country,City,Weight,Height,BMI,Birth Year,Current Year
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026
1,David,UK,London,78.0,1.75,25.5,1985,2026
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026
7,Lidiya,NaN,NaN,NaN,NaN,NaN,NaN,2026

In [248]:
df = df.rename(
    columns={
        "Name":"name",
        "Country": "country",
        "City": "city",
        "Weight":"weight",
        "Height":"height",
        "BMI":'bmi',
        'Birth Year':'birth_year',
        'Current Year':'current_year'
    }
)

In [250]:
df.weight.dtype

dtype('float64')

In [251]:
df.birth_year.dtype

dtype('O')

In [252]:
df.drop([7], axis = 0, inplace=True)
df['birth_year'] = df['birth_year'].astype('int')

print(df['birth_year'].dtype)

int64

In [253]:
df

,name,country,city,weight,height,bmi,birth_year,current_year
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026
1,David,UK,London,78.0,1.75,25.5,1985,2026
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026

In [254]:
df['age'] = df['current_year'] - df['birth_year']
df

,name,country,city,weight,height,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257
1,David,UK,London,78.0,1.75,25.5,1985,2026,41
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27

In [255]:
df_copy = df.copy()

In [256]:
df_copy

,name,country,city,weight,height,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257
1,David,UK,London,78.0,1.75,25.5,1985,2026,41
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27

In [266]:
print(type(df_copy.iloc[0]))
df_copy.iloc[1:]

<class 'pandas.core.series.Series'>

,name,country,city,weight,height,bmi,birth_year,current_year,age
1,David,UK,London,78.0,1.75,25.5,1985,2026,41
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27

In [271]:
mean = df_copy.iloc[1:]['age'].mean()

In [272]:
df_copy.iloc[0, 8] = mean

In [273]:
df_copy

,name,country,city,weight,height,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,36.5
1,David,UK,London,78.0,1.75,25.5,1985,2026,41.0
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36.0
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43.0
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41.0
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31.0
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27.0

In [280]:
df.iloc[0:, 0:4]

       name   country         city  weight
0  Asabeneh   Finland     Helsinki    74.0
1     David        UK       London    78.0
2      John    Sweden    Stockholm    68.0
3      Eyob   Finland        Espoo   108.0
4     Pawel    Poland       Warsaw   102.0
5    Mahlet  Ethiopia  Addis Ababa    58.0
6    Thomas  Ethiopia    Bahir Dar    52.0

In [282]:
df.iloc[0:, 0:4]

       name   country         city  weight
0  Asabeneh   Finland     Helsinki    74.0
1     David        UK       London    78.0
2      John    Sweden    Stockholm    68.0
3      Eyob   Finland        Espoo   108.0
4     Pawel    Poland       Warsaw   102.0
5    Mahlet  Ethiopia  Addis Ababa    58.0
6    Thomas  Ethiopia    Bahir Dar    52.0

In [288]:
df.iloc[[0]]

,name,country,city,weight,height,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257

In [286]:
print(type(df.iloc[[0]]))

<class 'pandas.core.frame.DataFrame'>

In [289]:
def classify_bmi(bmi):
    if bmi >= 30:
        return 'Obesity Range'
    elif bmi < 30 and bmi > 25:
        return 'Overweight Range'
    elif bmi < 25 and bmi >= 18.5:
        return 'Healthy Range'
    elif bmi < 18.5:
        return 'Underweight Range'

In [290]:
df

,name,country,city,weight,height,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257
1,David,UK,London,78.0,1.75,25.5,1985,2026,41
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27

In [291]:
df['bmi_class'] = df['bmi'].apply(lambda x: classify_bmi(x))

In [292]:
df

,name,country,city,weight,height,bmi,birth_year,current_year,age,bmi_class
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257,Healthy Range
1,David,UK,London,78.0,1.75,25.5,1985,2026,41,Overweight Range
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36,Healthy Range
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43,Obesity Range
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41,Overweight Range
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31,Healthy Range
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27,Underweight Range

In [293]:
df.iloc[0]

name                 Asabeneh
country               Finland
city                 Helsinki
weight                   74.0
height                   1.73
bmi                      24.7
birth_year               1769
current_year             2026
age                       257
bmi_class       Healthy Range
Name: 0, dtype: object

In [294]:
df.loc[0]

name                 Asabeneh
country               Finland
city                 Helsinki
weight                   74.0
height                   1.73
bmi                      24.7
birth_year               1769
current_year             2026
age                       257
bmi_class       Healthy Range
Name: 0, dtype: object

In [295]:
df

,name,country,city,weight,height,bmi,birth_year,current_year,age,bmi_class
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257,Healthy Range
1,David,UK,London,78.0,1.75,25.5,1985,2026,41,Overweight Range
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36,Healthy Range
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43,Obesity Range
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41,Overweight Range
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31,Healthy Range
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27,Underweight Range

In [296]:
df.loc[[0, 2, 4, 6]]

,name,country,city,weight,height,bmi,birth_year,current_year,age,bmi_class
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257,Healthy Range
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36,Healthy Range
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41,Overweight Range
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27,Underweight Range

In [300]:
df.loc[6, 'country']

'Ethiopia'

In [301]:
df.loc[0, 'age'] =

np.int64(257)

In [302]:
df.iloc[:]

,name,country,city,weight,height,bmi,birth_year,current_year,age,bmi_class
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257,Healthy Range
1,David,UK,London,78.0,1.75,25.5,1985,2026,41,Overweight Range
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36,Healthy Range
3,Eyob,Finland,Espoo,108.0,1.73,36.1,1983,2026,43,Obesity Range
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41,Overweight Range
5,Mahlet,Ethiopia,Addis Ababa,58.0,1.68,20.5,1995,2026,31,Healthy Range
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27,Underweight Range

In [303]:
# Boolean indexing
df.iloc[lambda x : x.index % 2 == 0]

,name,country,city,weight,height,bmi,birth_year,current_year,age,bmi_class
0,Asabeneh,Finland,Helsinki,74.0,1.73,24.7,1769,2026,257,Healthy Range
2,John,Sweden,Stockholm,68.0,1.69,23.8,1990,2026,36,Healthy Range
4,Pawel,Poland,Warsaw,102.0,1.95,26.8,1985,2026,41,Overweight Range
6,Thomas,Ethiopia,Bahir Dar,52.0,1.70,18.0,1999,2026,27,Underweight Range